# Generated by Django 5.0.3 on 2024-04-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contactform", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contactform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("subject", models.CharField(max_length=100)),
                ("message", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="ContactMessage",
        ),
    ]
