# Generated by Django 5.0.3 on 2024-04-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contactform", "0002_contactform_delete_contactmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactform",
            name="email",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="contactform",
            name="message",
            field=models.CharField(max_length=200),
        ),
    ]
