# Generated by Django 5.0.3 on 2024-04-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contactform", "0003_alter_contactform_email_alter_contactform_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactform",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="contactform",
            name="message",
            field=models.TextField(),
        ),
    ]
