# Generated by Django 5.0.3 on 2024-04-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="message",
            field=models.TextField(blank=True),
        ),
    ]
