# Generated by Django 4.2.6 on 2024-03-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_feedback_customer_name_feedback_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.AddField(
            model_name='feedback',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
